CREATE TABLE Hotel (
	ID INT AUTO_INCREMENT ,
	HOTEL_Name VARCHAR(50) NOT NULL,
	Tel VARCHAR(50) NOT NULL,
	Zip INT NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(Zip) REFERENCES Zip(Zip) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8