CREATE TABLE Department (
  Hotel_ID INT NOT NULL,
  Code INT NOT NULL,
  Tel VARCHAR(50) NOT NULL,
  PRIMARY KEY (Hotel_ID, Code),
  FOREIGN KEY (Hotel_ID) REFERENCES Hotel(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Code) REFERENCES Department_Code(Code) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8