CREATE TABLE Working_Time
(
    Working_Day VARCHAR(5) NOT NULL,
    Staff_ID INT NOT NULL,
    Start_Time TIME NOT NULL,
    End_Time TIME NOT NULL,
    PRIMARY KEY (Working_Day),
    FOREIGN KEY (Staff_ID) REFERENCES Staff (ID) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB DEFAULT CHARSET=utf8