CREATE TABLE Card (
	SERIAL VARCHAR(50) NOT NULL,
	BIN_Number VARCHAR(50) NOT NULL,
	Customer_ID INT NOT NULL,
	CVC INT NOT NULL,
	Validity DATE NOT NULL,
	Card_Password INT NOT NULL,
	PRIMARY KEY (SERIAL),
	FOREIGN KEY (BIN_Number) REFERENCES Card_BIN(BIN_Number) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Customer_ID) REFERENCES Customer(Customer_ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB CHARSET=UTF8;