CREATE TABLE Staff_Vacation
(
    Vacation_ID INT AUTO_INCREMENT  ,
    Staff_ID INT NOT NULL,
    Start_Day DATE NOT NULL,
    End_Day DATE NOT NULL,
    Staff_Type VARCHAR (50) NOT NULL,
    PRIMARY KEY (Vacation_ID),
    FOREIGN KEY (Staff_ID) REFERENCES Staff (Staff_ID) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=InnoDB DEFAULT CHARSET=utf8