CREATE TABLE Zip (
	Zip INT NOT NULL,
	Street_Number VARCHAR(50) NOT NULL,
	Street_Name VARCHAR(50) NOT NULL,
	City VARCHAR(50) NOT NULL,
	State VARCHAR(50) NOT NULL,
	PRIMARY KEY (Zip)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;