CREATE TABLE Course_Menu(
	Course_Name VARCHAR(50) NOT NULL,
	Hotel_ID INT NOT NULL,
	Restaurant_Name VARCHAR(50) NOT NULL,
	Price_Won INT NOT NULL,
	Appetizer VARCHAR(50) NOT NULL,
	Main1 VARCHAR(50) NOT NULL,
	Main2 VARCHAR(50) NOT NULL,
	Dessert VARCHAR(50) NOT NULL,
	PRIMARY KEY(Course_Name, Hotel_ID, Restaurant_Name),
	FOREIGN KEY(Hotel_ID) REFERENCES Hotel(Hotel_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Restaurant_Name) REFERENCES Restaurant(Restaurant_Name) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8