CREATE TABLE Parking_Lot (
	ZONE INT NOT NULL,
	Hotel_ID INT NOT NULL,
	Capacity INT NOT NULL,
	Max_Height_in_Meter INT NOT NULL,
	Valet_Parking_is_Able BOOLEAN NOT NULL,
	PRIMARY KEY(ZONE, Hotel_ID),
	FOREIGN KEY(Hotel_ID) REFERENCES Hotel(Hotel_ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8