CREATE TABLE Information (
	Inform_ID INT AUTO_INCREMENT,
	Zip INT NOT NULL,
	Apt_Num VARCHAR(50) NOT NULL,
	First_Name VARCHAR(50) NOT NULL,
	Last_Name VARCHAR(50) NOT NULL,
	E_Mail VARCHAR(50),
	Fax VARCHAR(50),
	Birthday DATE,
	Nationality VARCHAR(50) NOT NULL,
	Phone_Number VARCHAR(50) NOT NULL,
	Gender VARCHAR(50) NOT NULL,
	PRIMARY KEY (Inform_ID),
	FOREIGN KEY (Zip) REFERENCES Zip(Zip) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;