CREATE TABLE Card_BIN (
	BIN_number VARCHAR(50) NOT NULL,
	Bank VARCHAR(50) NOT NULL,
	Card_Type VARCHAR(50) NOT NULL,
	Rank VARCHAR(50) NOT NULL,
	Nation VARCHAR(50) NOT NULL,
	PRIMARY KEY (BIN_number)
) ENGINE=INNODB CHARSET=UTF8;