CREATE TABLE Room (
	Room_Num INT NOT NULL,
	Hotel_ID INT NOT NULL,
	Room_Type VARCHAR(50) NOT NULL,
	Is_Available BOOLEAN NOT NULL,
	Tel VARCHAR(45) NOT NULL,
	PRIMARY KEY(Room_Num, Hotel_ID),
	FOREIGN KEY(Hotel_ID) REFERENCES Hotel(ID) ON DELETE CASCADE ON UPDATE CASCADE, 
	FOREIGN KEY(Room_Type) REFERENCES Room_Type(Room_Type) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8